nname: Manuell kjøring på branch

on:
  workflow_dispatch:

jobs:
  build:
    env:
      IMAGE: europe-north1-docker.pkg.dev/nais-management-233d/tilgangsmaskin/${{ github.event.repository.name }}
      BASE: europe-north1-docker.pkg.dev/cgr-nav/pull-through/nav.no/jre:openjdk-25
    name: build
    permissions:
      checks: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/sisteBoot3'
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Kjør et eksempelsteg
        run: echo "Workflow kjører på branch sisteBoot3"
